apiVersion: apps/v1
kind: Deployment
metadata:
  name: rigup-db
spec:
  selector:
    matchLabels:
      app: rigupapp
  template:
    metadata:
      labels:
        app: rigupapp
    spec:
      containers:
      - name: database-server
        image: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: dbrigup
        ports:
          - containerPort: 3306