apiVersion: apps/v1
kind: Deployment
metadata:
  name: rigup-backend
  namespace: fpro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rigupapp
  template:
    metadata:
      labels:
        app: rigupapp
    spec:
      containers:
      - name: rigup-cont-backend
        image: abitsugar/rigup_backend:latest
        env:
          - name: DB_HOST
            value: svc-database
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: asdf1234zxc.
          - name: DB_NAME
            value: dbrigup
        ports:
        - containerPort: 2000
