apiVersion: v1
kind: Service
metadata:
  name: rigup-svc-backend
  namespace: fpro
spec:
  type: NodePort
  selector:
    app: rigupapp
  ports:
  - port: 2000
    targetPort: 2000
    nodePort: 30030
